logging:
  level:
    com.miguan: debug
    com.cgcg: debug
    com.baomidou.dynamic: debug
spring:
  redis:
    host: 112.74.179.254
    port: 6379
    password: e8cFnj3CoWZdUFyXg8Dkv9Vp66c=
    timeout: 15000
    database: 13
    jedis:
      pool:
        max-active: 10000
        max-idle: 100
        min-idle: 20
        max-wait: 3000
  datasource:
    dynamic:
      datasource:
        adv:
          url: jdbc:mysql://127.0.0.1:3306/ballvideoadv?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: advert_java
          password: 1r7Raa8lOwQCzuVa
          driverClassName: com.mysql.cj.jdbc.Driver
        dsp:
          url: jdbc:mysql://127.0.0.1:3306/dsp?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: dsp_java
          password: hpxpXjUAKzWFgn1A
          driverClassName: com.mysql.cj.jdbc.Driver
        report:
          url: jdbc:mysql://112.74.179.254:3306/ballvideoreport?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: zhangbinglin
          password: 5wMdNa45FS2xAMCj
          driverClassName: com.mysql.cj.jdbc.Driver
swagger:
  enable: true

bigdata-server:
  strategy:
    inIncentiveVideo: http://localdev.bdserver-java.uheixia.com/api/flow/strategy/inIncentiveVideo
    outIncentiveVideo: http://localdev.bdserver-java.uheixia.com/api/flow/strategy/outIncentiveVideo

xy-server:
  esFirstVideo:
    addOrDelete: http://localdev.xy.uheixia.com/api/es/firstVideo/addOrDelete
#推荐服务
new-rec:
  incentive-video: http://192.168.100.10