server:
  port: 8303
logging:
  level:
    root: info
spring:
  data:
    mongodb:
      bury:
        uri: mongodb://bdrep_java:gPCrW8cEpyoReWlc@192.168.0.206:53333/bp
      log:
        uri: mongodb://bdrep_java:gPCrW8cEpyoReWlc@192.168.0.206:53333/log
  redis:
    host: 192.168.0.211
    port: 6379
    password: NapBMeZfTCLbdYFXspgK0XnQ7vCzCQ6n
    timeout: 15000
    database: 2
    jedis:
      pool:
        max-active: 10000
        max-idle: 100
        min-idle: 20
        max-wait: 3000
  datasource:
    dynamic:
      datasource:
        report-db:
          url: jdbc:mysql://192.168.0.192:3306/ballvideoreport?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: bdrep_java
          password: AlGwK9A2K7eeQBgX
          driverClassName: com.mysql.cj.jdbc.Driver
        ad-db:
          url: jdbc:mysql://192.168.0.192:3306/ballvideoadv?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: bdrep_java
          password: AlGwK9A2K7eeQBgX
          driverClassName: com.mysql.cj.jdbc.Driver
        mofang-db: #需要生产给个报表的用户
          url: jdbc:mysql://rm-wz9r3k68fq34ck17n.mysql.rds.aliyuncs.com:3306/channel_tool_mofang?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: bdrep_java
          password: AlGwK9A2K7eeQBgX
          driverClassName: com.mysql.cj.jdbc.Driver
        video-db:
          url: jdbc:mysql://192.168.0.192:3306/ballvideo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: bdrep_java
          password: AlGwK9A2K7eeQBgX
          driverClassName: com.mysql.cj.jdbc.Driver
        ld-db:
          url: jdbc:mysql://192.168.0.198:3306/laidian?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
          username: bdrep_java
          password: AlGwK9A2K7eeQBgX
          driverClassName: com.mysql.cj.jdbc.Driver
        data-server:
          url: jdbc:mysql://192.168.0.245:3306/data_server?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
          username: bdrep_java
          password: AlGwK9A2K7eeQBgX
          driverClassName: com.mysql.cj.jdbc.Driver
        npush:
          url: jdbc:mysql://192.168.0.192:3306/npush?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: bdrep_java
          password: AlGwK9A2K7eeQBgX
          driverClassName: com.mysql.cj.jdbc.Driver
        clickhouse:
          url: jdbc:clickhouse://192.168.0.231:8123/ballvideostream?socket_timeout=600000
          username: bdrep_rw
          password: j1zIzDazBvX16lks
          driverClassName: ru.yandex.clickhouse.ClickHouseDriver
task:
  scheduled:
    cron:
      #每天凌晨5点
      export-adposition: 0 0 5 * * ?
      sta-video-add-offline: 0 0/10 * * * ?
      sync-rp-total-data: 0 0/5 * * * ?
      user-content-operation: 0 5,25,45 * * * ?
      user-ldcontent-operation: 0 15,35,55 * * * ?
      sync-user-keep: 0 10,40 * * * ?
      sync-lduser-keep: 0 20,50 * * * ?
      statistics-day-view: 1 0 0 * * ?
      statistics-hour-view: 0 0 0/1 * * ?
      sync-ldrp-total-data: 0 0/5 * * * ?
      sync-channel-detail: 0 10,40 * * * ?
      video-info: 0 0/5 * * * ?
      video-detail: 0 7,17,27,37,47,57 * * * ?
      pushresult: 0 0/8 * * * ?