server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    max-connections: 10000
spring:
  datasource:
    url: jdbc:mysql://192.168.100.10:3306/ballvideoadv?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: zhangbinglin
    password: 5wMdNa45FS2xAMCj
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 120000
      maximumPoolSize: 2500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  fifthdatasource:
    url: jdbc:mysql://112.74.179.254:3306/channel_tool_mofang?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: suhongju
    password: gWGcdZLTTw2hWSkf
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  thirdDataSource:
    url: jdbc:mysql://192.168.100.10:3306/ballvideoreport?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: zhangbinglin
    password: 5wMdNa45FS2xAMCj
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  dspdatasource:
    url: jdbc:mysql://192.168.100.10:3306/dsp?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: kangxuening
    password: htgfs0sHvqAS3a3X
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  redis:
    host: 192.168.100.10
    port: 6379
    password: 2ZfVUQPaVmKwdKWj6ZBW8CfvQt5EvK4C
    database: 12
    timeout: 15000
    jedis:
      pool:
        max-active: 10000
        max-idle: 100
        min-idle: 20
        max-wait: 3000
  session:
    store-type: redis
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
send:
  ndmin-java:
    url: http://dev.nadmin-java.uheixia.com
  abtest:
    # url: http://dev.abtest-go.98du.com
    url: http://58.23.3.114:9003
  abtest-php:
    userName: admin
    password: 123456
    url: http://localdev.abtest-php.98du.com
swagger:
  enable: true
logging:
  config: classpath:log4j2/Log4j2-local.xml
  level:
    com.miguan.advert.domain.mapper: debug


ding:
  robot:
    dataInfoUrl: http://localdev.bdserver-java.uheixia.com/api/addata/findEarlyWarnList
    secret: none
    accessToken: none