logging:
  level:
    root: info
    com.miguan.idmapping: info
spring:
  datasource:
    dynamic:
      primary: vedieo-db
      hikari:
        connectionTimeout: 180000
        maxLifetime: 60000
        validationTimeout: 8000
        idleTimeout: 50000
        min-idle: 20
        max-pool-size: 1500
      datasource:
        vedieo-db:
          url: jdbc:mysql://192.168.0.197:3306/ballvideo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: xyuid_java
          password: M7bvpz6uBR1dGWHr
          driverClassName: com.mysql.cj.jdbc.Driver
        task-db:
          url: jdbc:mysql://192.168.0.197:3306/ballvideotask?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: xyuid_java
          password: M7bvpz6uBR1dGWHr
          driverClassName: com.mysql.cj.jdbc.Driver
        clickhouse:
          url: jdbc:clickhouse://192.168.0.241:8123/ballvideostream
          username: default
          password: J7WnvXVM56kTSfqF
          driverClassName: ru.yandex.clickhouse.ClickHouseDriver
  redis:
    host: 172.18.161.166
    port: 6379
    password: e8cFnj3CoWZdUFyXg8Dkv9Vp66c=
    database: 4
    timeout: 15000
    jedis:
      pool:
        max-active: 10000
        max-idle: 300
        min-idle: 100
        max-wait: 3000
    redisson:
      config: classpath:/redisson/redisson-prod.yaml
  session:
    store-type: redis
  rabbitmq:
    addresses: 192.168.0.205
    username: xyuid
    port: 5672
    password: V3X7Lod23xEJHmrB
    open: true
  data:
    mongodb:
      uri: mongodb://idmap_java:RtZUDKb5f1v42Rpo@192.168.0.206:53333/?authSource=idmapping
      database: idmapping
  kafka:
    bootstrap-servers: 192.168.0.222:19092,192.168.0.223:19092,192.168.0.224:19092
    template:
      default-topic: uuid-digitizing
swagger:
  enable: false