logging:
  level:
    com.miguan: debug
    com.cgcg: debug
    com.baomidou.dynamic: debug
spring:
  redis:
    host: 192.168.100.10
    port: 6379
    password: 2ZfVUQPaVmKwdKWj6ZBW8CfvQt5EvK4C
    timeout: 15000
    database: 9
    jedis:
      pool:
        max-active: 10000
        max-idle: 100
        min-idle: 20
        max-wait: 3000
    bloom:
      init-capacity: 10000000
      error-rate: 0.0001
  datasource:
    dynamic:
      datasource:
        clickhouse:
          url: jdbc:clickhouse://192.168.100.10:8123/default?socket_timeout=300000
          username: bdserver_java_rw
          password: LhbFWgx1uMIh8p9G
          driverClassName: ru.yandex.clickhouse.ClickHouseDriver
        ck-dw:
          url: jdbc:clickhouse://192.168.100.10:8123/dw?socket_timeout=300000
          username: bdserver_java_rw
          password: LhbFWgx1uMIh8p9G
          driverClassName: ru.yandex.clickhouse.ClickHouseDriver
        report-db:
          url: jdbc:mysql://192.168.100.10:3306/ballvideoreport?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: bdrep_java
          password: XYU6hWevd6Nt9cT0
          driverClassName: com.mysql.cj.jdbc.Driver
        dsp:
          url: jdbc:mysql://192.168.100.10:3306/dsp?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: dsp_java
          password: 1w46dHftaN0k7Gbq
          driverClassName: com.mysql.cj.jdbc.Driver
        npush-db:
          url: jdbc:mysql://192.168.100.10:3306/npush?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: liyu
          password: iFZ62x7lrXufK4Cg
          driverClassName: com.mysql.cj.jdbc.Driver
        data-server:
          url: jdbc:mysql://192.168.100.10:3306/data_server?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: liyu
          password: iFZ62x7lrXufK4Cg
          driverClassName: com.mysql.cj.jdbc.Driver
        xy-db:
          url: jdbc:mysql://192.168.100.10:3306/ballvideo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: nrec_java
          password: iWEAFhlFKXUbxpEG
          driverClassName: com.mysql.cj.jdbc.Driver
        laidian-db:
          url: jdbc:mysql://192.168.100.10:3306/laidian?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: liyu
          password: iFZ62x7lrXufK4Cg
          driverClassName: com.mysql.cj.jdbc.Driver
        advert:
          url: jdbc:mysql://192.168.100.10:3306/ballvideoadv?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: zhangbinglin
          password: 5wMdNa45FS2xAMCj
          driverClassName: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      idmapping:
        uri: mongodb://bdserver_java:xQoZbRmnhdY8ZbHg@192.168.100.10:53333/idmapping
      drive:
        uri: mongodb://bdserver_java:xQoZbRmnhdY8ZbHg@192.168.100.10:53333/drive
  es:
    host: 192.168.100.10
    port: 19200
    host1: 192.168.100.10
    port1: 19200
#    host: 8.129.38.18
#    port: 9200
    scheme: http
  rabbitmq:
    addresses: 192.168.100.10
    port: 5672
    username: nrec
    password: VJsHFEE4t484Dv3W
    groupId: bigdata-service-localdev
    open: true
  kafka:
    bootstrap-servers: 192.168.100.10:19092
    template:
      default-topic: npush
swagger:
  enable: true