server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://192.168.100.10:3306/laidian?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: suhongju
    password: gWGcdZLTTw2hWSkf
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connectionTimeout: 600000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 3000
      idleTimeout: 60000
  seconddatasource:
    url: jdbc:mysql://192.168.100.10:3306/channel_tool_mofang?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: suhongju
    password: gWGcdZLTTw2hWSkf
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connectionTimeout: 600000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 3000
      idleTimeout: 60000
  thirdDataSource:
    url: jdbc:mysql://192.168.100.10:3306/ballvideoadv?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: suhongju
    password: gWGcdZLTTw2hWSkf
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  redis:
    host: 192.168.100.10
    port: 6379
    password: 2ZfVUQPaVmKwdKWj6ZBW8CfvQt5EvK4C
    database: 5
    timeout: 30000
    jedis:
      pool:
        max-active: 20000
        max-idle: 300
        min-idle: 100
        max-wait: 3000
    ballvideoDatabase: 6
    ballvideoHost: 112.74.179.254
    ballvideoPort: 6379
    ballvideoPassword: e8cFnj3CoWZdUFyXg8Dkv9Vp66c=
    ballvideoTimeOut: 30000
  session:
    store-type: redis
  data:
    mongodb:
      log:
        uri: mongodb://logjava:xCbxTG4PHWnq8Ncj@112.74.179.254:53333/log
      idmapping:
        uri: mongodb://ld_java:EC8XKMrnKovKEbSx@192.168.100.10:53333/idmapping
      ldpush:
        uri: mongodb://ld_java:EC8XKMrnKovKEbSx@192.168.100.10:53333/ldpush
  rabbitmq:
    addresses: 192.168.100.10
    username: laidian
    password: yALxF6eoyaT49BkK
    open: true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
swagger:
  enable: false
logging:
  config: classpath:log4j2/Log4j2-local.xml
push:
  auto-push:
    url: http://dev.bdrep.uheixia.com