server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://192.168.0.198:3306/laidian?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: laidian_java
    password: MelcTtPfAHk3pwTN
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connectionTimeout: 600000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 3000
      idleTimeout: 60000
  seconddatasource:
    url: jdbc:mysql://rm-wz9r3k68fq34ck17n.mysql.rds.aliyuncs.com:3306/channel_tool_mofang?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: xy_java
    password: 49HUwMKoeVC1qQpV
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connectionTimeout: 600000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 3000
      idleTimeout: 60000
  thirdDataSource:
    url: jdbc:mysql://192.168.0.197:3306/ballvideoadv?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: laidian_adv
    password: rNVRusg7FvJRlA3v
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  redis:
    host: 172.18.161.170
    port: 6379
    password: ljIrDdI6exTrukPSanfpvNk7PvxIBFii
    database: 5
    timeout: 30000
    jedis:
      pool:
        max-active: 20000
        max-idle: 300
        min-idle: 100
        max-wait: 3000
    ballvideoDatabase: 6
    ballvideoHost: 172.18.161.166
    ballvideoPort: 6379
    ballvideoPassword: e8cFnj3CoWZdUFyXg8Dkv9Vp66c=
    ballvideoTimeOut: 30000
  session:
    store-type: redis
  data:
    mongodb:
      log:
        uri: mongodb://logjava:xCbxTG4PHWnq8Ncj@112.74.179.254:53333/log
      idmapping:
        uri: mongodb://ld_java:HCSxdwF2xpzIkGwf@192.168.0.206:53333/idmapping
      ldpush:
        uri: mongodb://ld_java:HCSxdwF2xpzIkGwf@192.168.0.206:53333/ldpush
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: 172.18.161.166
    username: steps
    port: 5672
    password: nJBI1Q5VfkPeQX8D
    open: true
swagger:
  enable: false
logging:
  config: classpath:log4j2/Log4j2-prod.xml


push:
  auto-push:
    url: http://bdrep.uheixia.com