server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 5000
    max-connections: 10000
spring:
  datasource:
    url: jdbc:mysql://192.168.100.10:3306/ballvideo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: suhongju
    password: gWGcdZLTTw2hWSkf
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 120000
      maximumPoolSize: 2500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  seconddatasource:
    url: jdbc:mysql://192.168.100.10:3306/ballvideoadv?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: suhongju
    password: gWGcdZLTTw2hWSkf
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  thirdDataSource:
    url: jdbc:mysql://192.168.100.10:3306/shangbao?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: suhongju
    password: gWGcdZLTTw2hWSkf
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  fourthDatasource:
    url: jdbc:mysql://192.168.100.10:3306/channel_tool_mofang?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: suhongju
    password: gWGcdZLTTw2hWSkf
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  fiveDataSource:
    url: jdbc:mysql://192.168.100.10:3306/ballvideotask?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: suhongju
    password: gWGcdZLTTw2hWSkf
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  redis:
    #host: 120.78.185.45 外网地址
    host: 192.168.100.10
    port: 6379
    password: 2ZfVUQPaVmKwdKWj6ZBW8CfvQt5EvK4C
    database: 4
    timeout: 15000
    jedis:
      pool:
        max-active: 10000
        max-idle: 300
        min-idle: 100
        max-wait: 3000
    #上报redis数据源
    shangbaoDatabase: 1
    #47.112.149.132 外网地址
    shangbaoHost: 192.168.100.10
    shangbaoPort: 6379
    shangbaoPassword: 2ZfVUQPaVmKwdKWj6ZBW8CfvQt5EvK4C
    shangbaoTimeOut: 15000
    bloom:
      host: 192.168.100.10
      port: 6379
      password: 2ZfVUQPaVmKwdKWj6ZBW8CfvQt5EvK4C
      init-capacity: 10000000
      error-rate: 0.0001
      database: 9
    redisson:
      config: classpath:/redisson-localdev.yaml
  session:
    store-type: redis
  data:
    elasticsearch:
      cluster-name: ballVideo
      cluster-nodes: 192.168.100.10:9300
    mongodb:
      log:
        uri: mongodb://xy_java:OymdUupKHtnBBibU@192.168.100.10:53333/log
      feature:
        uri: mongodb://xy_java:OymdUupKHtnBBibU@192.168.100.10:53333/feature
      idmapping:
        uri: mongodb://xy_java:OymdUupKHtnBBibU@192.168.100.10:53333/idmapping
      xypush:
        uri: mongodb://xy_java:OymdUupKHtnBBibU@192.168.100.10:53333/xypush
      drive:
        uri: mongodb://xy_java:OymdUupKHtnBBibU@192.168.100.10:53333/drive
  service:
    predict:
      host: localdev.predict-java.uheixia.com
    recommend:
      host: 192.168.100.10:8380
    xyuid:
      host: localdev.xyuid.uheixia.com
    nconf:
      host: localdev.nconf-java.98du.com
  rabbitmq:
    addresses: 192.168.100.10
    username: xiyou
    port: 5672
    password: opI4NMfRxRO1I3RF
    open: true
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
send:
  abtest:
    url: http://localdev.abtest-go.98du.com
swagger:
  enable: true
logging:
  config: classpath:log4j2/Log4j2-localdev.xml
push:
  auto-push:
    url: http://dev.bdrep.uheixia.com