server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 5000
    max-connections: 10000

spring:
  datasource:
    url: jdbc:mysql://192.168.0.197:3306/ballvideo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: xy_java
    password: 49HUwMKoeVC1qQpV
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 120000
      maximumPoolSize: 2500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  seconddatasource:
    url: jdbc:mysql://192.168.0.197:3306/ballvideoadv?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: xy_java
    password: 49HUwMKoeVC1qQpV
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  thirdDataSource:
    url: jdbc:mysql://rm-wz9r3k68fq34ck17n.mysql.rds.aliyuncs.com:3306/shangbao?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: shangbao_java
    password: v1pXDjTlUKoUnaTv
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  fourthDatasource:
    url: jdbc:mysql://rm-wz9r3k68fq34ck17n.mysql.rds.aliyuncs.com:3306/channel_tool_mofang?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: xy_java
    password: 49HUwMKoeVC1qQpV
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  fiveDataSource:
    url: jdbc:mysql://192.168.0.197:3306/ballvideotask?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: xy_java
    password: 49HUwMKoeVC1qQpV
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 180000
      maximumPoolSize: 1500
      maxLifetime: 60000
      minimumIdle: 20
      validationTimeout: 8000
      idleTimeout: 50000
  redis:
    #host: 120.78.185.45 外网地址
    host: 172.18.161.166
    port: 6379
    password: e8cFnj3CoWZdUFyXg8Dkv9Vp66c=
    database: 4
    timeout: 15000
    jedis:
      pool:
        max-active: 10000
        max-idle: 300
        min-idle: 100
        max-wait: 3000
    #上报redis数据源
    shangbaoDatabase: 1
    #47.112.149.132 外网地址
    shangbaoHost: 192.168.0.204
    shangbaoPort: 6379
    shangbaoPassword: e8cFnj3CoWZdUFyXg8Dkv9Vp66c=
    shangbaoTimeOut: 15000
    bloom:
      host: 192.168.0.211
      port: 6379
      password: NapBMeZfTCLbdYFXspgK0XnQ7vCzCQ6n
      init-capacity: 100000000
      error-rate: 0.0003
      database: 9
  session:
    store-type: redis
  data:
    elasticsearch:
      cluster-name: ballVideo
      cluster-nodes: 192.168.0.210:9300
    mongodb:
      log:
        uri: mongodb://logjava:PGJTJ64FeN7rztys@192.168.0.206:53333/log
      feature:
        uri: mongodb://xy_java:XVjgCm9jlAfTW6lj@192.168.0.206:53333/feature?minpoolsize=32&maxpoolsize=1000
      idmapping:
        uri: mongodb://xiyou_java:CBotDmcDhXHQVYla@192.168.0.206:53333/idmapping
      xypush:
        uri: mongodb://xy_java:WO9phWWtwIiRbj1G@192.168.0.206:53333/xypush
      drive:
        uri: mongodb://xy_java:wesd2nBMTDwVxnkJ@192.168.0.206:53333/drive
  service:
    predict:
      host: 192.168.0.238:8306
    recommend:
      host: lan.nrec-java.98du.com
    xyuid:
      host: xyuid.uheixia.com
    nconf:
      host: nconf-java.98du.com
  rabbitmq:
    addresses: 192.168.0.205
    username: xiyou
    port: 5672
    password: REl1QCkkvpGICzSo
    open: true
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
send:
  abtest:
    url: http://abtest-go.98du.com
swagger:
  enable: false
logging:
  config: classpath:log4j2/Log4j2-prod.xml

push:
  auto-push:
    url: http://bdrep.uheixia.com